### ISSUE TITLE
Implement the pickup protocol: (1/4) Status Request query

### ISSUE THREAD

**Issue by Hermann-Core** [adorsys/didcomm-mediator-rs#102]
This issue is part of EPIC #42

**Comment by Christiantyemele** [comment]
This is closed by this Open
[Implement the mediator coordination protocol: Stateful (Pure didcomm) (1/3) Mediate Request -> Mediate Grant or Mediate Deny](https://github.com/adorsys/didcomm-mediator-rs/issues/79)
#79

**Comment by Hermann-Core** [comment]
Closes by #42
