### ISSUE TITLE
Improve Code Documentation for the Project

### ISSUE THREAD

**Issue by Hermann-Core** [adorsys/didcomm-mediator-rs#107]
The codebase lacks proper documentation, which makes it difficult to implement additional features. We often need to dig through the code to understand how it functions before we can use certain dependencies.

### Proposal:

1. **Document existing code**
 - Add docstrings to all public structs, enums, traits, and functions.
 - Include examples where applicable to demonstrate usage.
 - Add module-level comment explaining their purpose and functionality.
 - Write inline comments to explain non-obvious parts of the code.

2. **Update crate-level README**
 - Enhance the README file to provide a clear introduction to the package.
 - Include installation and usage instructions.
 - Add links to the detailed documentation where applicable.

3. **Generate API documentation**
 - Use the built-in tools like `cargo docs` to automatically generate and open the API documentation.

**Comment by Christiantyemele** [comment]
@Hermann-Core please can you add the estimation for the ticket
