### ISSUE TITLE
Complete refactor of the codebase

### ISSUE THREAD

**Issue by Hermann-Core** [adorsys/didcomm-mediator-rs#142]
complete refactoring of the codebase.

**Comment by Blindspot22** [comment]
@Hermann-Core I think you should also assign other people as reviewers. @francis-pouatcha and @IngridPuppet are always busy and Sometimes tickets spend days just on review which is not good.

**Comment by Hermann-Core** [comment]
> @Hermann-Core I think you should also assign other people as reviewers. @francis-pouatcha and @IngridPuppet are always busy and Sometimes tickets spend days just on review which is not good.

The tickets I’m working on impact the project significantly and are somewhat sensitive. Ingrid and Mr. Francis have a deeper understanding of the project since they’ve been working on it for several months. Be aware that some tickets may take several days or even weeks to review, depending on their complexity. Don’t worry Scott, you’ll be requested for review at the appropriate time 🙂.

**Comment by Blindspot22** [comment]
> > @Hermann-Core I think you should also assign other people as reviewers. @francis-pouatcha and @IngridPuppet are always busy and Sometimes tickets spend days just on review which is not good.
> 
> The tickets I’m working on impact the project significantly and are somewhat sensitive. Ingrid and Mr. Francis have a deeper understanding of the project since they’ve been working on it for several months. Be aware that some tickets may take several days or even weeks to review, depending on their complexity. Don’t worry Scott, you’ll be requested for review at the appropriate time 🙂.

That's true, but i find no big complexity in reviewing a refactoring ticket. By now i think we all have gained a base understanding of the project. By the way you where just refactoring the structure, deprecating some stuffs and documenting it, I'm saying this for better understanding of everybody and for faster improvement. I think we should be able to trust ourselves enough for the project before waiting for Francis and Ingrid.

**Comment by Hermann-Core** [comment]
It seems there may have been a misunderstanding about what I’m trying to say. Also, there’s no need to request to be a reviewer; the appropriate time will come. I’m not quite sure this discussion is adding value to this issue.
