### ISSUE TITLE
Some checks are lost on the unified route of the mediator coordination crate

### ISSUE THREAD

**Issue by IngridPuppet** [adorsys/didcomm-mediator-rs#144]
Looks like the following checks were lost on the unified route:

https://github.com/adorsys/didcomm-mediator-rs/blob/b8fd01ebe64ea0d4da853ceb4046b5dff0bde4dc/mediator-coordination/src/web/coord/handler/mod.rs#L34-L40

Add them to `stateful`, so it is not lost in the future. When done, I believe function `process_didcomm_mediation_request_message` could be safely removed.

https://github.com/adorsys/didcomm-mediator-rs/blob/b8fd01ebe64ea0d4da853ceb4046b5dff0bde4dc/mediator-coordination/src/web/coord/handler/mod.rs#L45-L56

**Comment by Blindspot22** [comment]
@IngridPuppet Apparently i did some findings with @Christiantyemele and discovered that this tacks has already been done earlier

**Comment by Blindspot22** [comment]
Seems like we should begin to do and overall ticket check every end of the month, cause some tacks are been done in other related  tickets while their original ticket lie in the Todo Bar
What do you think @IngridPuppet ?

**Comment by IngridPuppet** [comment]
> [@IngridPuppet](https://github.com/IngridPuppet) Apparently i did some findings with [@Christiantyemele](https://github.com/Christiantyemele) and discovered that this tacks has already been done earlier in another related ticket. I think i will just close the ticket if you are okay with it?

I created this ticket precisely because I noticed it was not completely done and required a dedicated ticket. Did you find the highlighted checks under `stateless::process_plain_mediation_request_over_dics`?

> Seems like we should begin to do and overall ticket check every end of the month, cause some tacks are been done in other related tickets while their original ticket lie in the `Todo Bar` What do you think [@IngridPuppet](https://github.com/IngridPuppet) ?

Most of the tickets in the Todo column are not actually coding tasks, neither are they to be prioritized. Anyway, we'll discuss this point with the Scrum master.

**Comment by Blindspot22** [comment]
> > [@IngridPuppet](https://github.com/IngridPuppet) Apparently i did some findings with [@Christiantyemele](https://github.com/Christiantyemele) and discovered that this tacks has already been done earlier in another related ticket. I think i will just close the ticket if you are okay with it?
> 
> I created this ticket precisely because I noticed it was not completely done and required a dedicated ticket. Did you find the highlighted checks under `stateless::process_plain_mediation_request_over_dics`?
> 
> > Seems like we should begin to do and overall ticket check every end of the month, cause some tacks are been done in other related tickets while their original ticket lie in the `Todo Bar` What do you think [@IngridPuppet](https://github.com/IngridPuppet) ?
> 
> Most of the tickets in the Todo column are not actually coding tasks, neither are they to be prioritized. Anyway, we'll discuss this point with the Scrum master.

Yes it's good
