### ISSUE TITLE
Create a mediation coordination client javascript client component.

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/didcomm-mediator-rs#208]
https://github.com/ADORSYS-GIS/didcomm-messaging-clients-utilities
https://www.npmjs.com/package/didcomm-node

**Comment by Christiantyemele** [comment]
![Screenshot from 2024-10-25 15-23-17](https://github.com/user-attachments/assets/a066568f-7a68-4417-881b-b3723deaeb4c)

Hello this is the current issue i am facing when while i was trying to debug the mediation-coordination, i suspects the error comes from the didcomm package of jest the test library but i have tried fixing with no success any help is welcomed
