### ISSUE TITLE
Write an article to compare the didcomm messaging infrastructure to the email infrastructure

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/didcomm-mediator-rs#214]
And show the key diferrence between email and didcomm messaging.
- https://www.varonis.com/blog/pgp-encryption#:~:text=Pretty%20Good%20Privacy%20(PGP)%20is,facto%20standard%20for%20email%20security.
- https://indicio.tech/didcomm-in-everyday-life/
- https://chatgpt.com/share/670e1e81-7878-800c-bda5-7a799c8c7961

**Comment by Christiantyemele** [comment]
This is the medium link
 
https://medium.com/@yemelechristian2/didcomm-messaging-vs-email-messaging-b98a3e116c82
