### ISSUE TITLE
Go through the handshake document and come up with tasks

### ISSUE THREAD

**Issue by hugoib** [adorsys/didcomm-mediator-rs#63]
Requested to review all documents related to a handshake process and then identify and list specific tasks that need to be completed based on those documents.

##### Objective

The ticket is asking for a comprehensive review and breakdown of the handshake document into actionable tasks. The result should be a clear and prioritized list of tasks that will guide further development and improvements related to the handshake process.

- [ ] Task related to #113 
- [ ] Task related to #99

**Comment by Blindspot22** [comment]
After reviewing the Lidonation documentation and Github Repository 

. https://www.lidonation.com/en/proposals/didcomm-v2-mediator-f8
. https://github.com/roots-id/didcomm-mediator

 The following tasks have been identified in other for the handshake process to be complete, with some partially implemented but requiring further work and improvement:

1. Define the handshake flow explicitly.
2. Enhance initial handshake request and response handling.
3. Validate and secure message exchange thoroughly.
4. Improve error handling mechanisms.
5. Optimize message transmission.
6. Enhance user feedback mechanisms.
7. Expand testing and validation.
8. Conduct interoperability testing.
