### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by Tekum-Emmanuella** [adorsys/didcomm-mediator-rs#85]
**Description:**

The current documentation provides a good overview of the conceptual framework but lacks instructions on how to run individual modules independently. This makes it difficult to onboard users into the  system.

**Suggestions for Improvement:**

* **Step-by-Step Guides:** Provide detailed instructions (with code examples) on how to set up and run each crate separately.
* **Configuration Options:** Explain how to configure individual crates and their dependencies.
* **Troubleshooting Tips:** Offer common issues and solutions users might encounter when running crates independently.
* **Examples:** Include practical examples demonstrating the use of individual crates in different scenarios.

**Comment by francis-pouatcha** [comment]
Please do not ofrget to mention that these hat to be installed to run the entire test:
# On ubuntu

sudo apt install pkg-config
sudo apt install libssl-dev

If possible please find out which of the modules need it and document ti there also.
